[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Download the Adafruit VL53L0X library and its dependencies
lib_deps = 
	adafruit/Adafruit_VL53L0X @ ^1.2.4